# Generated by Django 5.0.3 on 2024-03-28 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tg_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('password_hash', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(unique=True)),
                ('event_date', models.DateField(auto_now_add=True)),
                ('event_time', models.TimeField(auto_now_add=True)),
                ('event_details', models.TextField()),
                ('user_tg_id', models.OneToOneField(db_column='user_tg_id', on_delete=django.db.models.deletion.CASCADE, to='bot_admin.user', to_field='user_tg_id')),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
