# Generated by Django 5.0.3 on 2024-05-25 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='duration',
        ),
        migrations.AddField(
            model_name='meeting',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_admin.event'),
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_admin.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_admin.user')),
            ],
            options={
                'db_table': 'meeting_participants',
                'unique_together': {('meeting', 'user')},
            },
        ),
    ]
