# Generated by Django 5.0.3 on 2024-04-11 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user_count', models.PositiveIntegerField()),
                ('event_count', models.PositiveIntegerField()),
                ('edited_events', models.PositiveIntegerField()),
                ('canceled_events', models.PositiveIntegerField()),
                ('user_tg_id', models.OneToOneField(db_column='user_tg_id', on_delete=django.db.models.deletion.CASCADE, to='bot_admin.user', to_field='user_tg_id')),
            ],
            options={
                'db_table': 'botstatistics',
            },
        ),
    ]
