# Generated by Django 5.0.3 on 2024-05-27 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to='bot_admin.user', to_field='user_tg_id'),
        ),
    ]
