# Generated by Django 5.0.3 on 2024-05-27 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0002_alter_meeting_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='user_tg_id',
            field=models.ForeignKey(db_column='user_tg_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='bot_admin.user', to_field='user_tg_id'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to='bot_admin.user'),
        ),
    ]
