# Generated by Django 5.0.3 on 2024-04-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0003_alter_botstatistics_canceled_events_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botstatistics',
            name='user_tg_id',
        ),
    ]
