# Generated by Django 5.0.3 on 2024-05-22 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0004_remove_botstatistics_user_tg_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botstatistics',
            options={'verbose_name': 'botstatistics', 'verbose_name_plural': 'botstatistics'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('planner', models.CharField()),
                ('participants', models.CharField()),
                ('status', models.CharField(choices=[('CF', 'Confirmed'), ('CL', 'Canceled'), ('PD', 'Pending')], default='PD', max_length=3)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_admin.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_admin.user')),
            ],
            options={
                'verbose_name': 'meeting',
                'verbose_name_plural': 'meetings',
                'db_table': 'meeting',
            },
        ),
    ]
