# Generated by Django 5.0.3 on 2024-05-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0004_remove_meeting_organizer_remove_meeting_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
