# Generated by Django 5.0.3 on 2024-05-22 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0005_alter_botstatistics_options_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user_tg_id',
            field=models.ForeignKey(db_column='user_tg_id', on_delete=django.db.models.deletion.CASCADE, to='bot_admin.user', to_field='user_tg_id'),
        ),
    ]
